// tailwind.config.js
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        success: "#12B76A",
        primaryOp1: "var(--color-primaryOp1)",
        error: "#FF0000",
        errorOp1: "rgba(255, 0, 0, 0.1)",
        primaryOp2: "#12B76A1A",
        primaryOp3: "#FCEFE3",
        border: "#EAECF0",
        grey: "#D0D5DD",
        lightGrey: "#E5E5E6",
        bodyGrey: "#EBEEF2",
        base2: "var(--color-base2)",
        base3: "var(--color-base3)",
        base4: "var(--color-base4)",
        base: "var(--color-base)",
        main1: "var(--color-main1)",
        main2: "var(--color-main2)",
        main3: "var(--color-main3)",
        main4: "var(--color-main4)",
        main5: "var(--color-main5)",
        main6: "var(--color-main6)",
        secondary1: "var(--color-secondary1)",
        grey1: "var(--color-grey1)",
        grey2: "var(--color-grey2)",
        grey3: "var(--color-grey3)",
        grey4: "var(--color-grey4)",
        grey5: "var(--color-grey5)",
        grey6: "var(--color-grey6)",
        grey7: "var(--color-grey7)",
        inputMain: "var(--color-input-main)",
        primary2: "var(--color-primary2)",
        borderBase: "var(--color-border-base)",
        borderBase2: "var(--color-border-base2)",
        borderBase3: "var(--color-border-base3)",
        white: "#FFFFFF",
        baseBlack: "#1D1D1D",
        textMain: "var(--color-textMain)",
        textBase: "var(--color-text-base2)",
        footerBase: "var(--color-footer-base)",
      },
      textColor: {
        body: "#898E97",
        title: "#1D1D1D",
        grey: "var(--color-grey1)",
        grey2: "var(--color-grey2)",
        grey3: "var(--color-grey3)",
        grey4: "var(--color-grey4)",
        secondary: "#79F2C0",
        success: "#12B76A",
        main: "var(--color-text-base)",
        main2: "var(--color-base)",
        error: "#FC0114",
        errorOp1: "rgba(255, 0, 0, 0.1)",
      },
      placeholderColor: {
        main: "var(--color-text-base)", // Default placeholder color
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        md: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "28px",
        "4xl": "36px",
        "5xl": "48px",
      },
      fontWeight: {
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
      },
      fontFamily: {
        poppins: ["Poppins", "sans-serif"],
      },
      lineHeight: {
        16: "16px",
        20: "20px",
        21: "21px",
        22: "22px",
        24: "24px",
        28: "28px",
        40: "40px",
        50: "50px",
        52: "52px",
        70: "70px",
      },
    },
  },
  plugins: [],
}
